### ISSUE TITLE
Download is not working

### ISSUE THREAD

**Issue by ilbuonteo22** [abdulrahman1s/fem-dl#11]
Hi! First of all, thank you for your HUGE work..really!
I opened this issue because something seems to have changed from our FrontendMaster friends:
it looks like that the cookie `wordpress_logged_in_xxx` has changed and now it is called `fem_auth_mod` and the script no longer downloads.
Can you help us?
Thanks a lot!

**Comment by abdulrahman1s** [comment]
Thanks for reporting.
Fixed, try `npm fem-dl@latest`
