### ISSUE TITLE
Why is My Speed Limited to 0.25 MBPS 

### ISSUE THREAD

**Issue by sahillangoo** [abdulrahman1s/fem-dl#20]
Im using Windows 10 with Node v20 
My Downloading Speed is Capped to 0.25 MBPS is it for me or delebreatly ?

**Comment by supriome** [comment]
<img width="737" alt="image" src="https://github.com/abdulrahman1s/fem-dl/assets/19944032/479ba65f-5e96-41e5-b19f-c132d3513fb2">
