### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by sahillangoo** [abdulrahman1s/fem-dl#21]
Im using Windows 10 with node 20 and im getting this error while downloading

`Searching for svelte-v2...(node:7100) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit`

**Comment by ferdinandodanise** [comment]
Downgrade to node 18 and try
