### ISSUE TITLE
It is not installed, the error is this way. (npx fem-dl)

### ISSUE THREAD

**Issue by denemelikibo** [abdulrahman1s/fem-dl#3]
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/5210/lib/node_modules/fem-dl/node_modules/ffmpeg-static/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[############......] - install: info lifecycle ffmpeg-static@5.1.0~install: Failed to[############......] - install: info lifecycle ffmpeg-static@5.1.0~install: Failed to[############......] - install: info lifecycle ffmpeg-static@5.1.0~install: Failed to
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffmpeg-static@5.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffmpeg-static@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-01T21_35_04_217Z-debug.log
Install for [ 'fem-dl@latest' ] failed with code 1

**Comment by abdulrahman1s** [comment]
Hey, can you try again with pnpm? `pnpm dlx fem-dl` ([Install PNPM guide](https://pnpm.io/installation))

**Comment by denemelikibo** [comment]
C:\Users\fem\Downloads\Unity for Web Developers\4. Components\.tmp\index_2160p_Q10_20mbps\C# Custom Components\playlist.m3u8: Invalid data found when processing input

    at ChildProcess.exithandler (node:child_process:400:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'C:\\Users\\fem\\AppData\\Local\\pnpm\\store\\v3\\tmp\\dlx-12028\\node_modules\\.pnpm\\ffmpeg-static@5.1.0\\node_modules\\ffmpeg-static\\ffmpeg.exe -y -allowed_extensions ALL -i C:\\Users\\fem\\Downloads\\Unity for Web Developers\\4. Components\\.tmp\\index_2160p_Q10_20mbps\\C# Custom Components\\playlist.m3u8 -map 0 -c copy C:\\Users\\fem\\Downloads\\Unity for Web Developers\\4. Components\\.tmp\\index_2160p_Q10_20mbps\\C# Custom Components\\9. C# Custom Components.mkv'
}
 ERROR  Command failed with exit code 1: C:\Users\fem\AppData\Local\pnpm\store\v3\tmp\dlx-12028\node_modules\.bin\fem-dl.CMD

pnpm: Command failed with exit code 1: C:\Users\fem\AppData\Local\pnpm\store\v3\tmp\dlx-12028\node_modules\.bin\fem-dl.CMD
    at makeError (C:\Users\fem\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:22287:17)
    at handlePromise (C:\Users\fem\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:22858:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler [as dlx] (C:\Users\fem\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:199071:7)
    at async C:\Users\fem\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:206432:21
    at async run (C:\Users\fem\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:206403:34)
    at async runPnpm (C:\Users\fem\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:206624:5)
    at async C:\Users\fem\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:206616:7

**Comment by abdulrahman1s** [comment]
Can you paste the content of this playlist.m3u8 file? At can be located at ` C:\Users\fem\Downloads\Unity for Web Developers\4. Components\.tmp\index_2160p_Q10_20mbps\C# Custom Components\playlist.m3u8`

**Comment by denemelikibo** [comment]
File Explorer
Windows'C:\Users\fem\Downloads\Unity for Web Developers\4. Components\.tmp\index_2160p_Q10_20mbps\C# Custom Components\playlist.m3u8'
can't find it. Check the spelling and try again.
Okay

**Comment by abdulrahman1s** [comment]
Maybe because you targeting the file itself not its folder, try without the file name
 `C:\Users\fem\Downloads\Unity for Web Developers\4. Components\.tmp\index_2160p_Q10_20mbps\C# Custom Components\p`

**Comment by denemelikibo** [comment]
Same

**Comment by abdulrahman1s** [comment]
[v0.1.3](https://github.com/abdulrahman1s/fem-dl/releases/tag/v0.1.3) should fix your problem.

```p
$ npx fem-dl@v0.1.3
# or via pnpm
$ pnpm dlx fem-dl@v0.1.3
```
