### ISSUE TITLE
Crashing in middle of downloading 

### ISSUE THREAD

**Issue by gladiatorgiftson** [abdulrahman1s/fem-dl#4]
![image](https://user-images.githubusercontent.com/42843422/193447620-cfac8e5b-ac3e-4ecc-a797-082fad5f49df.png)

**Comment by gladiatorgiftson** [comment]
![image](https://user-images.githubusercontent.com/42843422/193448319-0b0d5080-3e74-4e91-a6e3-3fea895dede4.png)
 I am also getting this error

**Comment by abdulrahman1s** [comment]
It may related to bad internet connection. I'll implement retry on fail very soon.

**Comment by abdulrahman1s** [comment]
The latest version `v0.1.1` will solve your problem.
