### ISSUE TITLE
Hash function for mobile api?

### ISSUE THREAD

**Issue by Deshdeepak1** [abdulrahman1s/fem-dl#7]
I came here from your comment on https://github.com/20lives/FrontendMastersDownloader/
Do you have source code for this hash api,
https://fed-hasher.herokuapp.com/timestamp=
Its not working for 2.5.
Can you provide the source code, I want to update it
Or do you know how to generate it?

**Comment by abdulrahman1s** [comment]
Unfortunately no.
Plus, why would you want that? Isn't fem-dl working for you?

**Comment by Deshdeepak1** [comment]
The thing is in mobile app you can even watch few episodes of premium courses. In website only preview is allowed.
