### ISSUE TITLE
internalBinding('errors').triggerUncaughtException

### ISSUE THREAD

**Issue by miminas** [abdulrahman1s/fem-dl#9]
Any ideas what goes wrong here? (npx fem-dl@v0.1.3)

⠴ [0%] Downloading 3. React Patterns/15. Container/Presentation Pattern.mp4 | Size: 0KB | Remaining: 15/33
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

(Use `node --trace-uncaught ...` to show where the exception was thrown)

**Comment by abdulrahman1s** [comment]
I didn't handle child process (ffmpeg process) errors correctly
The latest version [v0.1.4](https://github.com/abdulrahman1s/fem-dl/releases/tag/v0.1.4) should display the error message.
try `npx fem-dl@v0.1.4` and post the error if any.

**Comment by miminas** [comment]
Results with v0.1.4

⠙ [0%] Downloading 3. React Patterns/15. Container/Presentation Pattern.mp4 | Size: 0KB | Remaining: 15/33
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^
ffmpeg version 5.0.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[hls @ 0x7fa2eb804ec0] Skip ('#EXT-X-VERSION:3')
[hls @ 0x7fa2eb804ec0] Opening 'https://speke.frontendmasters.com/BBgGhXjCmk-DlvLSejLDJ/549d5bdf-d210-4fee-a744-0c7b7b9b2d5b' for reading
[hls @ 0x7fa2eb804ec0] Opening 'crypto+https://stream.frontendmasters.com/2022/08/18/BBgGhXjCmk/DlvLSejLDJ/index_2160p_Q10_20mbps_00001.ts' for reading
Input #0, hls, from 'https://stream.frontendmasters.com/2022/08/18/BBgGhXjCmk/DlvLSejLDJ/index_2160p_Q10_20mbps.m3u8':
  Duration: 00:04:18.00, start: 2.000033, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
/Users/manolis/Downloads/A Tour of JavaScript & React Patterns/3. React Patterns/Container/Presentation Pattern.tmp.mp4: No such file or directory

(Use `node --trace-uncaught ...` to show where the exception was thrown)

**Comment by abdulrahman1s** [comment]
I got it. the problem is. there is a slash `/` within the episode name.
Give me a hour or so. I'll roll a release include a fix for that

**Comment by abdulrahman1s** [comment]
Fixed, `npx fem-dl@latest`
